{"uuid": "9e590375-7994-45e4-aff9-34a52f5a6f0b", "counter": 27, "stdout": "\u001b[1;31mfatal: [inventory.ini]: UNREACHABLE! => {\u001b[0m\r\n\u001b[1;31m    \"changed\": false,\u001b[0m\r\n\u001b[1;31m    \"msg\": \"Failed to connect to the host via ssh: debug1: OpenSSH_10.0p2, OpenSSL 3.5.0 8 Apr 2025\\r\\ndebug3: Running on Linux 6.14.2-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 10 Apr 2025 18:43:47 +0000 x86_64\\r\\ndebug3: Started with: ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=\\\\\\\\\\\"/home/mcmxcviii/.ansible/cp/e40c06ec51\\\\\\\\\\\" inventory.ini \\\"/bin/sh -c \\\\\\\\'echo ~ && sleep 0\\\\\\\\'\\\"\\r\\ndebug1: Reading configuration data /etc/ssh/ssh_config\\r\\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf depth 0\\r\\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf\\r\\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf depth 0\\r\\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf\\r\\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/mcmxcviii/.ssh/known_hosts'\\r\\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/mcmxcviii/.ssh/known_hosts2'\\r\\ndebug1: auto-mux: Trying existing master at '/home/mcmxcviii/.ansible/cp/e40c06ec51'\\r\\ndebug1: Control socket \\\"/home/mcmxcviii/.ansible/cp/e40c06ec51\\\" does not exist\\r\\ndebug2: resolving \\\"inventory.ini\\\" port 22\\r\\ndebug3: resolve_host: lookup inventory.ini:22\\r\\nssh: Could not resolve hostname inventory.ini: Name or service not known\",\u001b[0m\r\n\u001b[1;31m    \"unreachable\": true\u001b[0m\r\n\u001b[1;31m}\u001b[0m", "start_line": 50, "end_line": 55, "runner_ident": "91885d3f-181b-4fa4-b3af-483e576a064c", "event": "runner_on_unreachable", "pid": 128110, "created": "2025-04-14T22:02:43.477834+00:00", "parent_uuid": "38d57ae8-a7f1-0321-1679-000000000004", "event_data": {"playbook": "playbook.yml", "playbook_uuid": "dfcfcf2c-f211-4774-9fbb-b2978c54f9e4", "play": "Check server load", "play_uuid": "38d57ae8-a7f1-0321-1679-000000000002", "play_pattern": "all", "task": "Get system load information", "task_uuid": "38d57ae8-a7f1-0321-1679-000000000004", "task_action": "command", "resolved_action": "ansible.builtin.command", "task_args": "", "task_path": "/home/mcmxcviii/Documents/gh1/pg_install/playbook.yml:6", "host": "inventory.ini", "remote_addr": "inventory.ini", "start": "2025-04-14T22:02:43.449049+00:00", "end": "2025-04-14T22:02:43.477733+00:00", "duration": 0.028684, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: debug1: OpenSSH_10.0p2, OpenSSL 3.5.0 8 Apr 2025\r\ndebug3: Running on Linux 6.14.2-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 10 Apr 2025 18:43:47 +0000 x86_64\r\ndebug3: Started with: ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=\\\\\"/home/mcmxcviii/.ansible/cp/e40c06ec51\\\\\" inventory.ini \"/bin/sh -c \\\\'echo ~ && sleep 0\\\\'\"\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf\r\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/mcmxcviii/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/mcmxcviii/.ssh/known_hosts2'\r\ndebug1: auto-mux: Trying existing master at '/home/mcmxcviii/.ansible/cp/e40c06ec51'\r\ndebug1: Control socket \"/home/mcmxcviii/.ansible/cp/e40c06ec51\" does not exist\r\ndebug2: resolving \"inventory.ini\" port 22\r\ndebug3: resolve_host: lookup inventory.ini:22\r\nssh: Could not resolve hostname inventory.ini: Name or service not known", "changed": false}, "uuid": "9e590375-7994-45e4-aff9-34a52f5a6f0b"}}